# Generated by Django 5.1.5 on 2025-03-27 05:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_article_date_creation_article_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_publication',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notation',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notations', to='pages.article'),
        ),
    ]
